aalto/python.rst

There is a new Python environment available for groups that do analysis of neuroimaging data. This one is preferred over the old "brain" environment, as all the packages are up to date.

Update description of the "neuroimaging" python env

---

triton/apps/mathematica.rst

Can someone who knows about mathematica check this?  @aalto-kenny, do
you know, or know anyone who is an expert?

triton/apps/mathematica.rst: Update docs, Triton issue #561

---

triton/help.rst

- Let this commit message be a permament memory of how much we have
valued his time here.

triton/help.rst: Janne is leaving us

---

triton/help.rst

- To make support requests easier to act on.

triton/help.rst: Add "three rules of getting help"

---

aalto/jupyterhub-instructors/faq-hints.rst

- Note about how our nbgrader version is different from upstream, and
how to make them match.
- How to produce a usable environment.yml file from our conda environment.

jupyter.cs: nbgrader versions and note about how to get an environment file

---

aalto/jupyterhub-instructors/nbgrader.rst

- Since I see some people are using autograding, possibly without
realizing the security implications.

a/jh-i/nbgrader: Add dedicated section on limitations

---

aalto/jupyterhub-instructors/nbgrader-hints.rst

- It's officially supported now, so documenting by request.

a/jh/nbgrader-hints: Add documentation on instructor exchange

---

triton/tut/parallel.rst

- I realized that this provides some insight to the difference between
these.
- The rest of the page text may need improvement to explain this
distinction better - I'm not entirely sure (maybe before merging
this).

triton/tut/parallel: Add exercise to demonstrace -c/-n/-N

---

triton/usage/faq.rst

- Do we want the actual address written here, though?

triton/usage/faq: Update triton-users mailing list info

---

.github/workflows/checkwarnings.yaml
README.rst
meta/check-warnings.py

- This will emit a CI failure if there are warnings, for example
unknown link.
- We can make it a warning only and not a failure if needed, or adjust
the types of warnings.
- I welcome opinions on if this is a good idea.
- uses Github Actions

Add github action to check sphinx warnings

---

training/scip/shell-scripting.rst

- Timezone
- We accept remote participants but don't advertise too much now
- Mention git-bash, more information later

training/scip/shell-scripting.rst: include instructions for remote participation

---

triton/tut/modules.rst

I deleted the `But what about the software?` and added to the `What's next`.
Additionally created a new section for making a module collection. 
Also expanded the `what is a module?` section, and started off the `Loading modules`section with the Python example.
Overall tried to make it more organized and to give it a sensible flow.

restructures the sections

---

data/services.rst

- and fixup google description

data/services.rst: add dropbox

---

triton/index.rst
triton/tut/applications.rst

- The `Compilers and toolchains` section is removed.
- Minor re-sectioning and edits are applied s.t. this page precedes the `software modules` page.

removes toolchains and re-sections.

---

triton/tut/storage.rst

The first round of initial editing:
- Fixes sentencing and typos
- Reorganizes the sections
- Combines two of the exercises

re-organizes and fixes typos and sentencing

---

triton/tut/interactive.rst

- Resections and reorganizes the sections.
- Some material is excluded to be included in the `serial jobs` tutorial.
- Adds a little more code execution.
- The exercise session is left to be modified.

resections and reorganizes the text.

---

training/scip/summer-kickstart.rst

Links should be fine, I'll still need edit pages though.

Narvi links to fgci-kickstart page

---

index.rst

- I think this should be ready to go, but we should ensure the rse
section is ready.  I don't think it promises anything we can't do.

Add rse/ section to main page

---

scicomp/index.rst
scicomp/packaging-software.rst
triton/tut/applications.rst

- Lessons learned from HPC system administration and user support of
researchers who need to install things.
- To review:
- What is missing?
- It could use more links and references
- Is there something else that already exists that we should have
used instead?
- Links to recommendations about the actual coding part (which is
what most similar pages focus on)

scicomp/packaging-software: guide to make software easily installable

---

triton/tut/storage.rst

- In preparation for reorganizing the page.

triton/tut/storage: standardize heading levels

---

triton/tut/interactive.rst

- Fix an exercise to generalize to other sites.
- Other minor other fixups

triton/tut/interactive: minor revisions of the lesson

---

triton/tut/modules.rst

- new section on module versions
- misc revisions
- Add info on fgci-common metamodule

triton/tut/modules: minor edits and updates

---

triton/tut/applications.rst

- These shouldn't be hard, but get people used to looking at the docs
and searching the issue tracker, which is a good way to start.

triton/tut/applications: Add several exercises

---

triton/tut/interactive.rst

I added the address to the Github repo for the exercises and added a bit more information to them.

Revises exercises for the Interactive jobs tutorial page

---

training/scip/summer-kickstart.rst
triton/examples/openmp/hello_omp/hello_omp.c
triton/examples/openmp/hello_omp/hello_omp.slrm
triton/examples/python/python_openmp/python_openmp.py
triton/examples/python/python_openmp/python_openmp.rst
triton/examples/python/python_openmp/python_openmp.slrm
triton/tut/parallel.rst

This PR updates the parallel jobs tutorial page with various improvements.

Updating parallel tutorial pages

---

triton/tut/interactive.rst

- From https://hpc-carpentry.github.io/hpc-intro/13-scheduler/index.html
- Thanks to @sabryr for the idea - is this the right credit I should
give, or should I credit to HPC Carpnetry/sabryr?

triton/tut/interactive: Add HPC Diner analogy

---

rse/index.rst
rse/researchers.rst

- Give some concrete examples of what RSEs can do.
- Inspired by seeing someone who asked for a group seminar about
github, this kind of example would be really important for us.

rse/: give examples of how RSE service can be, e.g. group seminars

---

about/index.rst
about/join.rst

- Copy the old "how to join science-it" from science-it.aalto.fi
- Add another section on joining the RSE program
- Add section on university resources, and why someone would join if
you get some for free (time)
- To review: make sure that the wording is correct and everything is
phrased positively and clearly.  make sure we have a consistent
story.

about/join: Add join page, copied from old website

---

news/garage.rst

- Add the daily garage concept
- Move online to above summer
- Clean up some other text

news/garage: add daily garage

---

about/join.rst

- Separate from HPC and RSEs, we can have some sort of staff network.
Document this (even though we don't really know what it will be).
- To review: does it sound good?  Is it a good start?  It will have to
be iterated once people are back, and make sure it's what we want to
do.

about/join: Add description of "staff network"

---

about/for-proposals.rst

I was asked to make a sample text that can be used for funding
proposals which are data-focused.  We have a lot to offer here.
- This is a draft and I don't think it's very good yet - please help
revise.  I think they are missing most of the interesting things we
do, as well as just not being very organized.
- I also copied the "acknowledging Triton" part here - it doesn't
exactly go here but is somewhat related.

about/for-proposals: add "for proposals" text focusing on data

---

aalto/jupyterhub-instructors/faq-hints.rst
aalto/jupyterhub-instructors/news.rst
aalto/jupyterhub.rst

- Made possible by jupyterhub/jupyterhub#3013

aalto/jupyterhub: Direct link to courses

---

scicomp/zen-of-scicomp.rst

- Explains why we have a list of different topics
- To review: clarity and text (whole thing could take review, too, but
that's sfor another day)

scicomp/zen-of-scicomp: Add a section introducing the second half

---

training/scip/data-analysis.rst

Overhauled the data analysis course page for the upcoming 2020 course

training/scip/data-analysis: New 2020 course page

---

training/scip/python-for-sc.rst

- Reorganize this page to have the basics needed for registration:
prerequisites, updated dates, etc.
- To review:
- almost everything.
- Do we want to accept helper registration?

training/scip/python-for-sc: update page with course info

---

rse/community.rst

- Note it's also Triton powerusers group and point at editing
scicomp-docs itself.
- To review:
- Added Teams link - do we want this to be advertised?

rse/community: minor updates

---

news/garage.rst

- Simplify pages as much as possible
- Emphasize online

news/garage: Update garages for autumn

---

rse/become-a-rse.rst

- Remove "required" from the page, emphasize these are valued but we
combine the skills of many people.

rse/become-a-rse: make the skills list sound less scary

---

rse/index.rst

- Someone coming to this page may not have understood just how the
service will help them.
- To review:
- ensure it makes sense and has no errors.  Can it further
be improved?
- Can this be made even shorter and to the point

rse/index: Modify paragraph to directly say the benefit of RSEs.

---

scicomp/practical-git-prs.rst

- Talk about PR decriptions and what should go in them
- Mention CI checks
- To review: not much I think, general sanity check.

scicomp/practical-git-prs: PR descriptions and CI checks

---

aalto/linux.rst

- Has SSL now, looks very good and we should send everyone there.
- Review: not much

aalto/linux: Highlight linux.aalto.fi

---

training/scip/python-for-scicomp.rst

- Update lots of practical information
- Preparing to start the course

training/scip/python-for-scicomp: Update course information

---

rse/procedures/how-we-work.rst
rse/procedures/index.rst
rse/procedures/request.rst

- This is a first attempt at some user-facing instructions on how to
use our services.
- One, for how to request our services (link to Gitlab issue tracker)
- Two, how we work (what to expect, etc), based on the UCL guide I
found.  The point is to be a longer thing to let people know what to
expect when using our services.
- To review: everything, I haven't put much thought into this.  I
think we shouldn't try to make it perfect right now, but presentable
and then continue to iterate later.

Initial draft of RSE procedures pages

---

rse/procedures/implementation.rst
rse/procedures/index.rst

- This is our implementation document, as was submitted to funders for
approval.  It is the long-term vision document, which can be
incrementally updated.
- Review: Can have a general check, but most content has already been
reviewed by those who got the program started.

rse/procedures/implementation: Add draft from google drive

---

rse/procedures/index.rst
rse/procedures/job-descriptions.rst

- Write down an initial career ladder idea.  This is not so much
because it is needed for what it is (it is pretty standard), but to
give us something to discuss when planning the program.
- To review: everything, especially the content - though it is just a
draft.

rse/procedures/job-descriptions: Initial career ladder

---

training/scip/python-for-scicomp.rst

- Add all the actual instructors

training/scip/python-for-scicomp: Add all instructors

---

training/scip/data-analysis.rst

Adding more information on the course and adding url to course materials.

training/scip/data-analysis: Updating course information

---

training/scip/data-analysis.rst

- We have 134, close registration (but leave form open to get emails
about streaming)
- Review: general

training/scip/data-analysis: close registtration, direct to stream

---

aalto/jupyterhub-instructors/index.rst
aalto/jupyterhub.rst

I'm not sure if the syntax for adding a link is correct, would like somebody to double-check that

Misc typo fixes and a link to info about guru

---

about/join.rst
triton/accounts.rst
triton/help.rst
triton/tut/intro.rst

- grep and replace all occurrances of the email address
- One reference anchor changes name, I figure this is OK.
- I've also replaced it on our wiki

Update fro new email address

---

training/scip/data-analysis.rst

training/scip/data-analysis: Copy over template stuff from python-for-scicomp

---

training/scip/data-analysis.rst

- We say we need it, it should be mentioned somewhere

training/scip/data-analysis: add jupyterlab interface as prereq

---

rse/index.rst
rse/procedures/index.rst
rse/procedures/request.rst

- Review: minimial, mainly do we want the email exposed?

RSE: Add contact email address

---

rse/procedures/checklist-python.rst
rse/procedures/index.rst

- Add a checklist which I will use to start a RSE project on the right
track.  I can imagine some of these for different purposes, but we
should also see if theer are existing resources to point to.
- Review: check what is missing, but this is an iterative process so
it doesn't have to be perfect.

rse/procedures/checklist-python: add a Python-based checklist

---

scicomp/jupyter-pitfalls.rst

- Revisions throughout
- Organize solutions for each of the sections
- Add a new "don't separate people from other computational systems"
section.
- Preparing for a presentation on Wednesday.
- Review: general, a detailed read could be useful.

scicomp/jupyter-pitfalls: General page improvements

---

rse/procedures/job-descriptions.rst

- Describe future advancement possibilities better.
- Review: general read, does it make sense?

rse/procedures/job-descriptions: better describe future careers

---

rse/how-we-work.rst

- Review: it's worth thinking a bit more about these questions, and
this whole page in general (or at least the part that is known).

rse/how-we-work: Add list of some starting questions

---

rse/procedures/units-info.rst
rse/units.rst

- Review: do these pages make sense?  Could use proofreading.

rse/units: update info for units who may join

---

aalto/aaltostorage.rst
aalto/datapolicy.rst
triton/tut/storage.rst
triton/usagepolicy.rst

Explicit mention of individual user data deletion after 6 months from account expiry date.
Please improve the language if it seems unclear.

individual user data deletion

---

training/scip/data-analysis.rst

Added new links that point to the special assignment in course repository.

training/scip/data-analysis: Added link to the special assignment.

---

rse/how-we-work.rst
rse/procedures/implementation.rst
rse/procedures/time-tracking.rst

- When changing to a project, we have to charge only that work to that
project.  So we need a different way of handling the program
administration costs.
- Update various documents to reflect this
- Review: general check / does anything obviously not make sense?  It
will probably have to be iterated anyway, the process isn't fully
known yet.

rse: Update documents with information about overhead handling

---

help/index.rst

help/index: update link to sigma2 "asking for help"

---

rse/researchers.rst
rse/units.rst

- Someone suggested that "case studies" would be a good way to
introduce what the program can do, rather than long texts.  Add them
for researchers and units.
- Review: check if these are representative of what we do and somewhat
correct in wording.

rse: add case studies

---

rse/procedures/implementation.rst
rse/request.rst

Reworded a couple of sentences. I found these a bit confusing.
Review:
- Is what I wrote what you intended?
- Is it better?

Reword parts of the request and implementation pages

---

rse/units.rst

Review
- Is this what you meant
- language

Attempt to clarify project funding replacing departments share

---

rse/community.rst

Tried to make it more neutral and clarify

Reword who can join the RSE community

---

help/garage.rst
rse/index.rst
rse/request.rst

- Remove unneeded information, rearrange to make it more to the point.
- Target: help move people on the path from "visiting webpage" ->
"understanding" -> "being a customer".
- Review: general check, but worth more detailed reading, too.  Can be
iterated.

rse/: revise front matter based on discussion today

---

rse/index.rst

Small change. Review: Just check for typos.

Clarify that funding can come from a research project

---

rse/how-we-work.rst
rse/procedures/advisory-board.rst
rse/procedures/implementation.rst

- Review: minimial, these are discussed with departments and can be
updated later.

rse: list proposed KPIs under advisory board

---

training/scip/data-analysis.rst

training/scip/data-analysis: homework clarifications

---

rse/group-leaders.rst
rse/index.rst

- Mainly about funding and access to data, could be expanded.

rse: add "for group leaders" page about practicalities

---

aalto/zulip.rst

* Fix statement about external user support
* Add link to the test realm

Improvements to the Zulip page

---

rse/index.rst
rse/request.rst
rse/units.rst

- Review: general check, ensure this is what we want.

rse/: Link to servicedesk form, change to rse-group email address

---

scicomp/ssh.rst

scicomp/ssh: explain the use of the ssh config file

---

aalto/zulip.rst

* Add mention about chat instance lifespan and Spring 2021 semester.
* Add mentions about usage in grading and for internal/confidential
data.

Update the zulip page

---

aalto/zulip.rst

tarkensin alkuun, ja RC pois. LIsäksi tuesta pitäisi ehkä sanoa jotain? Ja chatit voisi tilata lomakkeella, niin saisimme kerättyä yhteen paikkaan tilastoa tarpeista. Lomakkeesta saa sähköpostinotifikaation, jonka voi lähettää guruun eli RT-tiketiksi.

pilottiin liittyvää ja RC pois

---

aalto/zulip.rst

I'm not sure about the markup, though... :/

the request form address

---

rse/procedures/time-tracking.rst

- Review: also consider if this makes sense

rse/procedures/time-tracking: Update descriptions of timetracking data

---

help/index.rst

- Add zulipchat (the main prompting of this)
- Structure it a bit more like "what team" rather than general
principles.  Emphasize our own contact methods.
- Allow linking to each of our main contact methods, by making them
sections.
- Review: worth a more detailed read and proofread.

help/index: major revision of the page

---

help/garage.rst

- Hold in review until approved by the team.
- Review: check for accuracy

help/garage: update for winter holidays

---

about/for-proposals.rst

- We needed a RSE text which can be included in grant applications.
This is the start of that.
- Review: this isn't very good yet, and I found it hard to make
something very general that can be copied and pasted like the other
text on this page.  Please give it a careful read and revise it as
much as you can.

about/for-proposals: Add RSE section

---

training/index.rst
training/scip/intro-linux-aalto-computing.rst

- Draft, at everything is still to be discussed.  Even dates could be
changed.
- Please review for both semantics and syntax.

Add "Intro to Linux and computing" course page

---

triton/accounts.rst

triton/accounts: link to account creation form

---

aalto/aaltostorage.rst
aalto/linux.rst
aalto/welcomestudents.rst

- Found all spots by grep (I hope)

Aalto home quota increased to 100G

---

training/scip/winter-kickstart.rst

- Copy by standard template to this page, update the introductiory
material
- This is better than it was before, but still needs many iterations
- Review: mainly the intro paragraphs.

training/scip/winter-kickstart: Update page

---

scicomp/packaging-software.rst

- A recent conversation got me thinking about problems in
dependencies.  I have thus elaborated on it some here.
- Review:
- Is this on-topic and correct?
- Does this make it too long?

scicomp/packaging-software: Write a bit more about dependencies

---

training/scip/intro-linux-aalto-computing.rst

training/scip/intro-linux-aalto-computing: update date (one week later)

---

training/scip/intro-linux-aalto-computing.rst

training/scip/intro-linux-aalto-computing: switch order of the parts

---

training/index.rst
training/scip/index.rst
training/scip/intro-linux-aalto-computing.rst
training/scip/winter-kickstart.rst

- Moved past courses to archive
- Added registration link for kickstart

Update of training pages

---

training/scip/intro-linux-aalto-computing.rst

- Based on what we know now, refine the target audience some more.
- Review: general read, see if there is any more to adjust.

training/scip/intro-linux-aalto-computing: revise course description

---

training/scip/intro-linux-aalto-computing.rst

training/scip/intro-linux-aalto-computing: Revise description of course parts

---

training/scip/winter-kickstart.rst

- Quick links
- install time
- etc...

training/scip/winter-kickstart: Update course info

---

rse/request.rst

- If you follow the link and have to pass through the login form, the
direct link doesn't work!

rse/request: Give the title of the button to click

---

training/scip/intro-linux-aalto-computing.rst
training/scip/winter-kickstart.rst

Small updates with link to Helsinki Uni resources

---

triton/tut/intro.rst

- Review: Is this factually correct?

triton/tut/intro: Add Ship of Theseus metaphor for Triton

---

training/scip/winter-kickstart.rst
triton/index.rst
triton/tut/about-tutorials.rst

- Comment on differences to other sites
- Review: worth a read, is everything correct?

Add a general intro to the tutorial series

---

triton/ref/index.rst
triton/tut/applications.rst

- Revise in general
- Move common software to the quick ref
- Review: general

triton/tut/applications: revise page

---

triton/tut/connecting.rst

- Minor updates and rearrangements

triton/tut/connecting: revise tutorial

---

scicomp/shell.rst

- Variables are actually a quite important part of basic shell usage,
at least when following other examples it is useful to know $NAME
syntax.  Quickly introduce it here.
- Review: worth a detailed read: is there anything that can be
removed?  Anything missing?

scicomp/shell: Add section on variables

---

training/scip/intro-linux-aalto-computing.rst
triton/apps/matlab.rst
triton/apps/python.rst
triton/apps/r.rst
triton/index.rst
triton/tut/about-tutorials.rst
triton/tut/applications.rst
triton/tut/array.rst
triton/tut/connecting.rst
triton/tut/gpu.rst
triton/tut/interactive.rst
triton/tut/intro.rst
triton/tut/modules.rst
triton/tut/parallel.rst
triton/tut/serial.rst
triton/tut/storage.rst

- Linked on every page individually, plus the whole playlist
- Review:
- Does making too many links mean that it will be hard to maintain
in the future, when there are new videos?

triton/tut/: Link videos from winter kickstart 2021

---

aalto/zulip.rst

- User reported it was unclear
- Review: is it clear and correct?

aalto/zulip: Clarify invitation setting section

---

triton/apps/gurobi.rst

We could document the gurobi license server at least.

Add Gurobi optimizer

---

help/index.rst

- To get more users for Aalto Zulip
- Review: does this belong here?

help/index: Add link to zulip for courses

---

images/levels.svg
training/index.rst
training/scip/index.rst
training/scip/matlab-advanced.rst
training/scip/shell-scripting.rst
training/scip/software-design.rst

Adding more courses not organized by us. Adding registration links that were missing.

More links!

---

help/index.rst
triton/help.rst

- A complicated request may never be answered becaues it takes too
long to think about the solution, where some initial advice or "this
will take too long, we recommend you find another solution" would be
fine and fast.
- Inside motive: find a way to reduce the number of issues which are
never answered, or only answered after a very long time, because
they take too long.
- Review:
- Is four too many key questions for a summary?
- Review of wording, in particular can it be made shorter?

Asking for help: add fourth question about "what do you need"

---

aalto/python.rst

Made sure our docs point to the newest versions of the neuroimaging environment. Also removed some old stuff that is no longer relevant.

Update Neuroimaging environment documentation

---

triton/usage/faq.rst

I wasn't able to find it anywhere else

documenting "module load git"

---

triton/usage/singularity.rst

The basic things I learned are now reported here. Unfortunately the Serpent source code is closed, so I can't really make a nice tutorial kind of presentation. One could consider writing a separate Serpent page and just add a link.

Add a story about Singularity+MPI (Serpent)

---

training/scip/summer-kickstart.rst

- As currently written in planning
- Mainly I updated day 1, day 2-3 are roughly like before and needs
more edits later.
- Review:
- general check, incremental work but this makes it look more correct

training/scip/summer-kickstart: Update schedule from HackMD

---

training/scip/summer-kickstart.rst

- Discussed with Enrico during garage

training/scip/summer-kickstart: Schedule update based on garage discussions

---

rse/index.rst

- Review: check text for accuracy

rse/index: Add link to NVAITC

---

training/scip/summer-kickstart-intro.rst
training/scip/summer-kickstart.rst
training/scip/summer-kickstart/intro.rst

- Inspired by CodeRefinery's intro
- Review: syntax and content, but it is iterative.

training/scip/summer-kickstart-intro: Add a basic intro

---

help/index.rst
help/user-groups.rst

- This page describes our idea of user groups, what they do, and how
people can start.
- Review: is this the general idea we want to do?

Add draft user group page

---

training/scip/summer-kickstart.rst
training/scip/summer-kickstart/video-summary.rst

- Minimal text, to be improved later
- Review: read, comment on what might be missing.  OK to merge and improve later.

summer-kickstart/video-summary: Notes for the video summaries

---

training/scip/summer-kickstart.rst
training/scip/summer-kickstart/future.rst

- Notes on the "your future career" portion
- Direct copy from HackMD planning, needs more work and elaboration
- Review: comment on what else could be added.  OK to merge and improve later.

summer-kickstart/future: Notes on the future portion

---

training/scip/summer-kickstart/intro.rst

- Make a general pass over the intro material
- Review: general read

training/scip/summer-kickstart/intro: General revisions

---

triton/examples/monitoring/gpu.rst
triton/examples/monitoring/seff.rst
triton/index.rst
triton/tut/gpu.rst
triton/tut/monitoring.rst
triton/tut/parallel.rst
triton/tut/serial.rst

This PR adds a new chapter on how to monitor jobs. It is placed between serial jobs and array jobs.

New chapter triton/tut/monitoring

---

triton/tut/storage.rst

vdi paths and other paths

---

training/scip/summer-kickstart.rst

updating day2 for the best

---

triton/apps/julia.rst
triton/ref/software.rst
triton/tut/applications.rst

Updated applications page to include more information on how to find applications.
Other changes:
- Added Julia to the list of commonly used software
- Made quality of life improvement to Julia-page

triton/tut/applications: Updated applications page

---

triton/examples/array/array_example.sh
triton/examples/array/pi_array_grouped.sh
triton/examples/array/pi_array_hardcoded.sh
triton/examples/array/pi_array_parameter.sh
triton/examples/monitoring/seff.rst
triton/ref/examples-repo.rst
triton/tut/array.rst
triton/tut/interactive.rst
triton/tut/monitoring.rst
triton/tut/serial.rst

THis PR contains various improvements to the materials of kickstart day 3.

Kickstart updates day3

---

triton/tut/array.rst
triton/tut/gpu.rst
triton/tut/parallel.rst

This PR reorganizes some of the exercises and does some minor adjustments to array-, parallel- and gpu-pages.

Kickstart exercise updates day3

---

rse/become-a-rse.rst
rse/community.rst

Small fixes of typos and such.

rse/community and rse/become-a-rse: Small fixes

---

rse/become-a-rse.rst

- Make a "role-based" section, deemphasize skill list
- Add more links

rse/become-a-rse: Further clarifications

---

triton/apps/gurobi.rst

This PR adds information on Gurobi usage in Python and Julia.

triton/apps/gurobi: Update Gurobi page with newer infrormation.

---

rse/become-a-rse.rst
rse/index.rst

- Job ad: get information out there.
- Videos: explain why we do what we do.

rse/: Add job advertisement link + links to videos

---

scicomp/ssh.rst

scicomp/ssh: Reorder links

---

rse/index.rst

- This is focused now on how we do it, not the technical skills we have.
- Review: general check of clarity

rse/index: Revise the lead text based on taxonomy of three things we do

---

help/garage.rst

- Add link to ITS garage
- Shorten some other information, comment out now-redundant in-person
information
- Review
- How should we distinguish the IT Services garage from ours?

help/garage: Update, add ITS link

---

rse/researchers.rst

Review:
- Is this the right place?
- Standard language check

Add a note about RSE service for students

---

training/julia/julia-introduction.rst

New dates for the Julia course

Schedule the Julia course for october 4-5

---

aalto/jupyterhub-instructors/index.rst
aalto/jupyterhub-instructors/overview.rst

- This serves as the best available nbgrader user guide.
- Review: general check / automerge

aalto/jupyter-instructors/: Add more promenent links to Noteable documentation

---

triton/apps/matlab.rst

A couple of words about matlab workers and dangers when running multiple jobs.

Parpool workers hints

---

rse/grant-applicants.rst

- Better instructions for budgeting as salary
- General other fixups
- Review: general check for now, does it in general make sense?  I
will confirm factual nature separately.

rse/grant-applicants: Update page based on current knowledge

---

aalto/jupyterhub-instructors/index.rst
aalto/jupyterhub-instructors/testing-a-course.rst

- Add some general instructions on testing a course.  Present
different options.
- Review: general check, see if any testing options are missing.

jh-instructors/testing-a-course: new page on testing

---

triton/tut/storage.rst

- As seen in garage today
- Review: someone should still check this

triton/tut/storage: Clarify windows "map network drive" instructions

---

training/julia/julia-introduction.rst

Add Julia course audience info and suggested read

---

scicomp/hybrid-events.rst
scicomp/index.rst

- Collected from another chat and published here, since we have no
other good place to put them.
- Review: general check, but can be continually improved so doesn't
need to be perfect.

Add hybrid event recommendations

---

help/garage.rst

- Review: check warnings/automerge

help/garage: Update formatting of top part (it was rendered as a definition list)

---

triton/apps/importantnotes/matlab.rst
triton/apps/matlab.rst
triton/examples/matlab/int_parallel.rst
triton/examples/matlab/parpool_parallel.rst
triton/examples/multilang/matlab/collectResults.m
triton/examples/multilang/matlab/serial.m
triton/examples/multilang/matlab/serial_array.m
triton/examples/multilang/matlab/serial_base.m

Updating Matlab app-page examples to use newer examples. and Adding an addition notice to parfor section

Update matlab app-file with newer examples

---

aalto/zulip.rst
aalto/zulip/instructors.rst

- Student and instructor docs improvements, based on feedback.

aalto/zulip: More doc info based on feedback.

---

triton/ref/modules.rst

There are this two useful commands to list and get the details on the users' saved collections and they should be also listed in this table.

Adding collection information commands

---

triton/usage/faq.rst

- These probably got added sometime long ago, when I was first making
the page.

triton/usage/faq: remove several duplicate entries

---

triton/tut/interactive.rst

- Thanks to @JMuff22.  Please approve this PR since it is registerd
with your `Author:` credit.

triton/tut/interactive: Fix link to hpc-carpentry

---

triton/index.rst

Reordering the Triton table of content, removing duplicate entries and grouping some things.

Reordering and removing duplication

---

triton/tut/serial.rst

- Ideas from Simo
- The idea is it might be good to show that these environment
variables exist.  But it may not be worth taking time from the main
flow.  Making it an advanced exercise means that the people who have
time and mental energy can explore it.
- Review: text and "is this a good idea?"

triton/tut/serial: advanced exercise to show job env variables

---

training/scip/getting-started-with-scientific-computing.rst
training/scip/winter-kickstart.rst

This PR contains some changes to the winter kickstart-course's & getting started-session's schedules.

Winter kickstart schedule

---

training/scip/winter-kickstart.rst

- As discussed in the meeting today
- Also add in "real-life examples of different languages", which we
did one year and turned out well.
- Review: see if these are good descriptions or anything else makes
sense.

training/scip/winter-kickstart: Add final topis to day 3

---

training/scip/winter-kickstart.rst

I changed the title to something more understandable for large audience. I have also added instructions for Oulu.

added oulu site + title change

---

training/scip/winter-kickstart.rst

This PR changes schedules around and differentiates different topic blocks

training/scip/winter-kickstart: Schedule update

---

rse/index.rst

- This semi-checklist is a good thing to review when packaging
software.

rse/index: Add link to /scicomp/packaging-software in checklist section

---

triton/apps/python.rst

Add instructions on how to install conda environments to work folder.

triton/apps/python: Work folder instructions

---

triton/ref/index.rst
triton/ref/remotedata.rst

- Triton rsync and sftp transfers
- Triton mount paths
- Review: someone should read the text

triton/ref: Add remotedata quick reference (transferrs and mounts)

---

training/scip/getting-started-with-scientific-computing.rst

Adding links to Tools of Scientific Computing-materials.

winter-kickstart: Tools of Scientific Computing-materials

---

training/scip/getting-started-with-scientific-computing.rst
training/scip/winter-kickstart.rst

kickstart course video links

---

triton/ref/connecting.rst
triton/tut/connecting.rst
triton/usage/ood.rst

- Review: general check or merge quickly

OOD notes: add to connecting ref, note about VPN, small revisions of instructions

---

triton/tut/dependency.rst

triton/tut/dependency: make exercises sphinx-lesson

---

triton/tut/remotedata.rst
triton/tut/storage.rst

triton/tut/{storage,remotedata}: improve links both ways

---

aalto/remoteaccess.rst
triton/tut/remotedata.rst

Updated the remote access pages with tabs for each OS, containing the actual info for that OS.

Update connection instructions for different OS, to reflect the OS 

---

aalto/remoteaccess.rst
triton/tut/remotedata.rst

- Dedent the tab boxes last lines so that they are outside of the
bullet points
- other whitespace cleanup in these files (M-x whitespace-cleanup)

remote data whitespace cleanup

---

training/scip/software-design-2022.rst

updated description to fit the updated assignment (for April 2022 course), increased ECTS to 2

Updated software design course description

---

about/index.rst

@tpfau, can you check your entry and suggest specialties?

Remove Marijn and Essi, Add Thomas to /about

---

about/for-proposals.rst

- It wasn't clear enough to that one needed to adapt this

about/for-proposals: add more warnings to the boilerplate page

---

about/for-proposals.rst

about/for-proposals: Update "don't use as-is" warning based on RES feedback

---

rse/procedures/job-descriptions.rst

- As we thought about within one of our meetings

rse/procedures/job-descriptions: Add beyond RSE3 ideas based on ideas

---

training/scip/data-anonymization-workshop-2022.rst

- This gets rid of a warning and simplifies maintenance (I normally
recommend this kind of table for anything complex... this or
csv-table).

training/scip/data-anon2022: Make the table a list-table

---

training/index.rst
training/scip/debugging-2022.rst
training/scip/matlab-advanced-2022.rst
training/scip/software-design-2022.rst
training/scip/summer-kickstart-2022.rst

I tested it locally, it builds. I have tested most of the links and they are fine. We can merge and revise eventualy

updates for spring 2022

---

training/scip/summer-kickstart-2022.rst

training/scip/summer-kickstart-2022: Front matter update, things are more known

---

training/scip/kickstart-2022-summer.rst

- I had done a lot of improvements on the winter kickstart page, which
needed to be moved back to the summer page.  (it's annoying to have
to do tihs every year).  So, I am trying to merge the pages once and
for all.
- I tried to combine them.  Things may not be perfect, but it can be
followed up later.

kickstart-2022-summer: Update from winter kickstart page

---

training/scip/kickstart-2022-summer.rst

training/scip/kickstart-2022-summer: Further improvements, day 1 from winter

---

training/scip/kickstart-2022-summer.rst

- More incremental work of the whole course page (but not the schedule)

kickstart-2022-summer: Revise course description

---

training/scip/kickstart-2022-summer.rst

- Make a quick reference at top, tune to getting more partners

training/scip/kickstart-2022-summer: Adjust top matter

---

triton/usage/faq.rst

triton/usage/faq: Add bashrc + module warning for graphical applications

---

scicomp/ssh.rst

Forgot to update the Info that this now also works for windows machines (which was the whole point of it)...

Also available for windows now

---

rse/become-a-rse.rst

- The old page was too much of a list of skills, which as we know
turns many people off.
- Try to make it more inclusive, and instead focus on "incremental
steps you might take to improve" rather than "here is the end
state."  Hopefully that is more open, and also it provides a path
forward to people who want to do this.
- Review: general read, or in practice merge + iterate.

rse/become-a-rse: Heavily revise page to make it sound more inclusive.

---

triton/apps/jupyter.rst

Update instructions to install R versions for Jupyter.

Jupyter for r

---

training/scip/kickstart-2022-summer.rst

Just a small update to the SSH sections text which sounded like it was the text from the full cluster workflow from earlier

Update SSH promo-text

---

triton/examples/monitoring/gpu.rst
triton/examples/monitoring/seff.rst
triton/ref/connecting.rst
triton/ref/slurm.rst
triton/ref/slurm_status.rst
triton/ref/storage.rst
triton/tut/applications.rst
triton/tut/array.rst
triton/tut/dependency.rst
triton/tut/gpu.rst
triton/tut/interactive.rst
triton/tut/modules.rst
triton/tut/monitoring.rst
triton/tut/parallel.rst
triton/tut/remotedata.rst
triton/tut/serial.rst

- After discussion about what the best meta-variables syntax is, this
is what I thought was the least bad.  Not perfect, but uniform and
easy to interpert for new users with a one-to-one character
replacement with what they should do.
- Review: confirm this is something we want to do.

Change metavariables no N uniformly, instead of <n> and $n

---

triton/tut/applications.rst

- It wasn't clear what the actual question was, so try to clarify.

triton/tut/applications: Clarify tensorflow exercise

---

triton/apps/python-conda.rst
triton/apps/pytorch.rst
triton/apps/tensorflow.rst
triton/examples/pytorch/pytorch_with_conda.rst
triton/examples/tensorflow/tensorflow_with_conda.rst

Update Tensorflow and PyTorch documentation. 
Get the respective app pages up to date about how to set up environments that install GPU enabled versions.

Tensorflow update

---

triton/apps/jupyter.rst
triton/examples/python/simple_python_gpu.sh

Noticed some typos and consistency issues, which are fixed by this PR.

Fixing typos, adding consistency

---

tech/index.rst
tech/user-support-responses.rst
tech/user-support.rst

- My notes from my years of experience + observing people, written by
request of someone.
- Unsure if this is obvious or not, but we can start collecting ideas
somewhere, I guess.
- Review:
- general reading, any further ideas to add?
- This is incomplete so far

tech/user-support-responses: Based on request, "how to answer user requests"

---

training/index.rst
training/scip/index.rst

training/index: Update course list, move old courses to the archive page

---

rse/index.rst

- Find from some RSE blog somewhere, I think
- I am not sure how useful it is, it doesn't seem that detailed to me,
but maybe better than nothing.
- Is there a better link compared to this?
- Review: someone who knows matlab should see if this is useful and
preferably find a better link.

rse/index: Add checklist for matlab reproducibility

---

news/index.rst

no straight push to master since I cannot run a test render right now

updating news

---

requirements.txt

- sphinx!=5.2.0.post0 because of bug in sphinx_rtd_theme, remove after
next release
- Un-pin other changes which are hopefully no longer needed

requirements: Update for latest standards

---

training/scip/python-for-scicomp-2022.rst

very cool how forking and sending PR now is automated on GitHub!

add myself and fix typo

---

aalto/jupyterhub-instructors/request-course.rst

- Adding some extra reminders there

aalto/jh-instructors/request-course: Some updates for request form

---

training/scip/python-for-scicomp-2022.rst

I will automerge in 1h, opening a PR anyway to test the edits

added how to get 1 credit

---

triton/usage/faq.rst

- Answer as found in garage
- Review: please give it a good read

triton/usage/faq: Info on LC_* environment variables

---

training/scip/python-for-scicomp-2022.rst

it would be good to check that I didnt forget anyone

updated list of instructors + helpers

---

help/garage.rst

- Review: check accuracy and phrasing

help/garage: winter 2022/2023 availability notes

---

about/sustainability.rst

- Based on a conversation I had yesterday, it's actually pretty cool
that we can make a concsious decision between ewaste generation and
electricity usage more finely grained than other clusters.

about/sustainability: Minor update, emphasize ewaste/electricity tradeoff

---

triton/apps/gurobi.rst

This is an update to the gurobi page with current information.
Things might change soon if there is an update to the license.

Updating gurobi page

---

rse/index.rst
rse/procedures/prioritization.rst
rse/researchers.rst

- As discussed, this is an initial attempt at explaining how we
prioritize RSE projects.
- Review: worth reading everything for detailed comments (then merge
and iterate at some point)

rse/prioritization: Starting description of how we do it

---

rse/portfolio.rst

Adding an example of help with parallelisation

Adding parallelisation example

---

triton/apps/lammps.rst
triton/examples/lammps/build/build_basic.rst
triton/examples/lammps/build/build_most.rst
triton/examples/lammps/indent/lammps_indent.rst
triton/examples/lammps/indent/lammps_indent.sh

This PR has new build and run instructions for LAMMPS.

triton/apps/lammps: Major update to LAMMPS documentation

---

rse/index.rst
rse/researchers.rst
rse/units.rst

- This is something that was hinted, but based on a talk I just saw
the idea of public preview interfaces should be emphasized even
more.  ChatGPT provides a good example that everyone knows about
now.
- Review: what's the right terms to describe this, especiall for the
index page?  I'm not quite happy with my descriptions.

rse: Preview interfaces are a high-impact service.

---

training/index.rst

Updating courses

---

aalto/python.rst

- Minimum solution, but possibly there could be more discussed about
this topic and Python on Aalto Linux in general.
- Review: check for accuracy and if it still matches what the current
build system expects.

aalto/python: Solution to NotWriteable error message

---

rse/index.rst

- Found on mastodon, seem relevant
- Review: automerge and/or check if they seem useful

rse/index: Link packaging guides from pyopensci/ropensci

---

triton/apps/vscode.rst
triton/ref/index.rst

- As discussed in garaget today

triton/apps/vscode: vscode interactive tutorial

---

rse/how-we-work.rst

- "starting a project" - more thoughts on scheduling practicalities

rse/how-we-work: Comments on RSE scheduling

---

scicomp/git-annex.rst

- Based on mastodon threads.
- Review: check accuracy, check if the RDM-focus is justified, check
if it should be even more strongly recommended than is written here.

scicomp/git-annex: Add mentions of DataLad

---

about/for-proposals.rst

Minor change to update cloud platform dates

Fix GCP date & AWS estimate

---

triton/tut/cluster-shell.rst

- Now has exercises and more text
- Review: worth reading it

triton/tut/cluster-shell: Fill out tutorial

---

triton/ref/connecting.rst
triton/tut/connecting.rst

- Slight arrangement at top (adding more to the abstract).
- Hide SSH config file in dropdown box, emphasize checking the SSH page
- Solutions to exercises
- Minor other updates
- Review: worth reading it

triton/tut/connecting: Improve tutorial

---

triton/tut/applications.rst

- Instead of tool-based approach, go over categories: stuff already
installed, stuff we install, stuff you need to install yourself.
This hopefully is nicer and more useful to read.
- Most important stuff is still there, but I reomved some stuff that
seemed excessively verbose.
- Review: worth a read

triton/tut/applications: Revise for kickstart

---

triton/tut/cluster-shell.rst
triton/tut/serial.rst
triton/tut/slurm.rst

- General revisions, nothing too big
- Move away "partitions" now, add a shorter version to slurm
- Review: worth a read

triton/tut/serial: further update, minimize now that slurm page exists

---

triton/tut/cluster-shell.rst

Adds solutions to couple of exercises in shell tutorial.

Add model solutions to exercises.

---

triton/tut/modules.rst

Added solutions to exercises 1-3 and 6 on modules page. 
Exercises 4 and 5 could use some revisions first, so I didn't add anything to them yet.

Added solutions to some of the exercises.

---

training/scip/kickstart-2023.rst

I turned the box into a TL;DR with relevant info. Please improve

updating the important green box with TL;DR

---

triton/examples/monitoring/gpu.rst
triton/tut/monitoring.rst

triton/tut/gpu: Minor edits based on the plan

---

triton/tut/applications.rst
triton/tut/array.rst
triton/tut/cluster-shell.rst
triton/tut/connecting.rst
triton/tut/interactive.rst
triton/tut/intro.rst
triton/tut/modules.rst
triton/tut/monitoring.rst
triton/tut/prerequisites.rst
triton/tut/remotedata.rst
triton/tut/serial.rst
triton/tut/slurm.rst
triton/tut/storage.rst

- This PR is too big, but I'm tired from all the changes.  Separating
out would be too much work.
- Most things here are as discussed, and also I have previewed most of
it.
- I think it might be worth merging and reviewing after the fact.

triton/tut: big update based on today's discussions

---

triton/ref/examples-repo.rst
triton/tut/array.rst
triton/tut/dependency.rst
triton/tut/interactive.rst
triton/tut/modules.rst
triton/tut/monitoring.rst
triton/tut/parallel-mpi.rst
triton/tut/serial.rst
triton/tut/storage.rst

Work in progress branch for more model solutions. Currently has some for serial and monitoring tutorial. I'll continue iterating on current ones and adding more, but any feedback is appreciated.

Adding model solutions to exercises

---

triton/tut/array.rst
triton/tut/cluster-shell.rst
triton/tut/connecting.rst
triton/tut/gpu.rst
triton/tut/interactive.rst
triton/tut/intro.rst
triton/tut/parallel-mpi.rst
triton/tut/parallel-shared.rst
triton/tut/parallel.rst
triton/tut/remotedata.rst
triton/tut/serial.rst
triton/tut/slurm.rst
triton/tut/storage.rst

- Original figures by Thomas, red boxes and stuff by me.

triton/tut/: Add our schematic figures to represent what we are talking about.

---

triton/tut/gpu.rst
triton/tut/parallel-mpi.rst
triton/tut/parallel-shared.rst

This PR contains exercises for the parallel pages.

Kickstart 2023 parallel exercises

---

aalto/python.rst

- Got a support request wondering about laptop stuff and why this
didn't work.

aalto/python: Note about laptops + Python

---

training/scip/linux-shell-basics-2023.rst

Added page description and registration. Please review if you have time.

Linux shell August 2023

---

training/index.rst
training/scip/linux-shell-basics-2023.rst
training/scip/workflows-2023.rst

Just updates, no major changes

Training updates for autumn 2023

---

aalto/aaltoharbor.rst
aalto/index.rst

Adds new page under Aalto section about the new Harbor service.

Harbor: User guide 

---

scicomp/ssh.rst

- Generalize the page, since SSH config and keys are going to become
much more important in the future.
- Better explain all the key options for connecting on different
operating systems.

scicomp/ssh: Updates throughout the SSH page

---

triton/apps/vscode.rst

- Various assorted updates.  Not yet reviewed in detail.

triton/apps/vscode: Further VSCode updates

---

data/index.rst
data/plans.rst

- Found in some quick checks
- Review: OK to merge right away

Fix two links in the data section

---

data/index.rst

Update index.rst - Updating my fork

---

aalto/remoteaccess.rst

Also replaces `taltta` with `viila`.

remoteaccess: Recommend ProxyJump instead of ProxyCommand

---

aalto/aaltodata.rst

- Related: #674 (but doesn't completely fix, there's a bit more once a
page is published).

aalto/aaltodata: Fix broken link

---

triton/acknowledgingtriton.rst

- Having a good set of photos is useful, and during the yearly "add
papers to ACRIS" time would be reasonable to request people send us
good ones.
- Review: see if this is a good idea.

triton/acknowledgingtriton: Add request for photos

---

triton/apps/orca.rst
triton/examples/orca/orca_example.sh

This PR adds a new application page for ORCA.

triton/apps/orca: Adding a new documentation page for ORCA

---

triton/apps/llms.rst

This PR will add a new page about LLMs.
Currently it contains information about the module system we have for different models.

triton/apps/llms: Adding a new page about LMMs

---

triton/usage/faq.rst

- While this is a big, wide question, this is some of the initial
ideas that we usually use for debugging.
- The FAQ is as much for us to remind ourselves the main debugging
strategies than to expect a typical person with a problem to be able
to decipher it.
- Review: worth a good discussion in garage, since most of this is
from memory.

triton/usage/faq: Initial FAQ about things like `GLIBCXX_3.4.26' not found`

---

triton/ref/modules.rst
triton/tut/modules.rst

- Since we have some hierarchical modules now, document it.
- Review: quick read, add one exercise using them.

triton/tut/modules: Update for hierarchical modules

---

tech/index.rst

Add my FCCI Python package talk to the list.
Review:
- Spelling and links

Add FCCI tech talk

---

_meta/redirects.txt
conf.py
requirements.txt

- Allows HTML redirects
- Don't merge yet, still deciding if this is a good idea and works.

Add redirects using sphinxext-rediraffe

---

aalto/zulip.rst

- selective following/muting
- push notifications
- notn pilot

aalto/zulip: Some updates based on recent news

---

triton/accounts.rst

triton/accounts: New account policy for 2024

---

training/scip/kickstart-2024.rst

Change narvi URL on the kickstart page

---

training/scip/kickstart-2024.rst
triton/usage/faq.rst

PR to quickly check if anything needs fixing, otherwise automerge in the next 24 hours.

large update to Day 1

---

triton/apps/speech2text.rst

Clean up speech2text user guide by removing obsolete notes and warnings.

Update the speech2text user guide

---

triton/apps/python-conda.rst
triton/apps/tensorflow.rst
triton/examples/pytorch/pytorch_with_conda.rst
triton/examples/tensorflow/tensorflow_with_conda.rst
triton/ref/conda.rst
triton/ref/index.rst

- Use the mamba command everywhere it works
- Slight adjustments in order of sections/rows and
- Adjust section underlines to make them more standard for other docs
- Unfortunately this means some other docs had to be updated (it
seemed that some included files were making top-level headings in
this page, which perhaps wasn't intended.  At least I think it
shouldn't be relied on)

Triton Conda/Mamba updates

---

rse/history.rst

- Direct cause: asked for a link to how our team started
- Indirect uses: I've often needed to tell people about the motavition
for our team, how we got it through, and our early history.  This
shows a lot of those basics.

rse/history: Add a brief history of Aalto RSE and its motivations

---

data/index.rst

- This table would be quite useful to us, since it's the most
importart question that users have to make (and are often confused
about).
- Minor revisions on the rest of the page

data/index: Add a summary table at the top, for the most important questions

---

data/index.rst
triton/tut/storage.rst

Added some links in the data index page. 
Could probably be even more in the table but before I add those I would like to know if you think this is a good idea.

More data updates

---

training/scip/ttt4hpc-2024.rst
triton/tut/applications.rst
triton/usage/singularity.rst

when renaming it I assumed the URL would forward but I was wrong

URL changed for one lesson (sorry)

---

triton/examples/monitoring/gpu.rst
triton/ref/slurm_status.rst
triton/tut/gpu.rst
triton/tut/monitoring.rst

- Should it be Ave (average) or another field?
- Should we go straight to slurm2sql?

Update for GPU monitoring using TRESUsageInAve

---

aalto/jupyterhub-data.rst
aalto/jupyterhub-instructors/faq-hints.rst
aalto/jupyterhub-instructors/system-environment.rst
aalto/linux.rst
scicomp/python.rst
triton/apps/gurobi.rst
triton/apps/python-conda.rst
triton/apps/python.rst

- Minimize mentions of Anaconda where it's easy.  Make it clear it's
not a default.

Minimize mentions of anaconda

---

triton/ref/index.rst
triton/ref/quotas.rst
triton/usage/quotas.rst

- This makes the quota inspectio and fixing commannds more visible.
- Review: does the quick ref need to be shorter?

Add a "quotas" section to /triton/ref, also mention personal vs project quotas

---

triton/examples/monitoring/gpu.rst
triton/tut/gpu.rst

- Modified GPU requesting information. Now different methods are outlined.
- Made some chapters more visible with header changes.
- Added mention of seff-gpu to the monitoring.

gpu: Small updates to GPU pages for the winter kickstart 2025.

---

triton/tut/array.rst

This PR updates array exercise 1 to be in a smaller scale and fixes some paths.

triton/tut/array: Updating the array exercise 1
