about/rse.rst
- I got a comment that the page doesn't emphasize data enough - and
this is true.  I addded some.
- I left the name "Research Software Engineer" in most places, but in
the introduction put "Research Software/Date Engineer".  It should
be clarified, any thoughts on this?
- Anything more to add here?
=> about/rse.rst: Add comments indicating an equal focus on data

about/rse.rst
- We should connect RSEs to our courses, and emphasize that this is a
hands-on kickstart.
=> about/rse.rst: Add sentence describing relation to other training

aalto/jupyterhub-data.rst, aalto/linux.rst, aalto/paniikki.rst, aalto/python.rst, aalto/remotejupyter.rst, aalto/welcomestudents.rst, triton/apps/jupyter.rst, triton/apps/keras.rst, triton/apps/python.rst, triton/apps/tensorflow.rst, triton/examples/cntk/cntk_mnist.rst, triton/examples/python/ipyparallel/ipyparallel.slrm, triton/examples/python_openmp.rst, triton/examples/pytorch/pytorch_mnist.rst, triton/examples/pytorch/pytorch_mnist.sh, triton/examples/tensorflow/tensorflow_mnist.rst, triton/examples/tensorflow/tensorflow_mnist.sh, triton/tut/applications.rst, triton/tut/gpu.rst, triton/tut/modules.rst, triton/tut/serial.rst
- Some initial changes done
figure stuff out.
making own environments
- Anyone else can work on this, and it doesn't have to be perfect
before merging.
=> Triton: begin revising for anaconda3->anaconda

triton/apps/sjupyter.rst
- With diskless nodes, there isn't a good way to install local things
to /usr/local/bin (there probably is, but I don't know it).  So, I
made sjupyter available as a module.  It would be better if this was
in some default paths, but oh well.
- This has to be not just in path, but in the same path on all nodes.
I had done some stuff with linking to put it in /usr/local/bin
linked to NFS software, but that no longer works on diskless nodes.
- I could continue to manually install this on the login nodes, but
this doesn't scale and isn't managed...
=> triton/a/sjupyter: note that sjupyter is available as a module

triton/apps/jupyter.rst
This pull request updates jupyter instructions to use new installed IRkernel.
=> triton/apps/jupyter.rst: Revised R instructions to use new installed IRkernel.

aalto/jupyterhub-instructors/faq-hints.rst, aalto/jupyterhub-instructors/request-course.rst
- This service seems stable enough that it can be generally
recommended.  Thanks to Markus for seeing it through.
=> aalto/jh-instructors/: document self-service for adding TAs

aalto/jupyterhub-data.rst, aalto/jupyterhub-instructors/course-data.rst, aalto/jupyterhub-instructors/faq-hints.rst, aalto/jupyterhub-instructors/system-environment.rst
- Mention that `kinit` may be needed to access files on shell servers.
- Link to the newly-revised coursedata page from more locations.
=> jupyter.cs: mention kinit for file access, link to data description more

Dockerfile, _templates/footer.html, conf.py, meta/requirements.txt
- Use extension sphinx_gitstamp to do this.  Basically everything
works automatically, but we need to manually put it into the footer.
- This is written to not fail if the extension is not installed, to
make this as easy to build as possible.
- Untested on readthedocs so far.
=> Add page timestamp at the bottom from git

triton/tut/connecting.rst
I removed the `Transferring files` section since it wasn't closely associated with how to connect to  Triton. I additionally moved the part about changing the shell closer to the exercise that alluded to it. Overall I tried to make it more compact and to the point.
=> reorganizes the sections

triton/apps/cosmol.rst
triton/apps/cosmol.rst: minor fixups
triton/apps/cosmol.rst: use -launcher slurm and -clustersimple
- This is what people on our issue tracker use, e.g. #691.  With a
user we tested and it seems to actually use the requested number of
CPUs.
- Using -c seems better than -n in this situation, we thought in our
garage today.  It's what others do at least.
triton/apps/cosmol.rst: fix linking the .cosmol dir
- We need to not have trailing slash, or it expects it place it there
(-T), not in that directory.
=> cosmol: various fixups

scicomp/ssh.rst
I rewrote the page based on my notes while first setting up an account on Triton, focusing on the Linux/Mac user. There are a few things I'd like some feedback on.
- I'd like some help making the issue of typing in passwords even with ssh-keys clearer. Ubuntu 18.04 is storing it permanently for me, but standard ssh-agent only lasts for a single machine session.
- I'd like to propose adding a page that includes the SHA256 &/or randomart images for the various Linux servers so students don't breeze on by the WARNING when first logging into a machine.
=> Updating the SSH page in docs

scicomp/ssh.rst
- The `::` for code blocks needs a blank line after it.
- If used as the last thing in a paragraph, it becomes a single colon
which is sort of nice for presenting the part below.
=> Fix some sphinx warnings

triton/tut/serial.rst
I updated the text and reorganized the sections. Some extra examples of Slurm commands are added.
There are a few to-dos I'd like your input on. 
- I'd like to add some more structured rules of thumb about setting resource parameters (more specific details on how long/large jobs should be).
- Is the reference page on partitions updated (partitions, number of nodes, etc.)?
- I'd additionally like to write a simple code sample (just as in `interactive.rst`) that require some logging and I/O.
There will be further synchronization between the `Interactive jobs`, `Serial jobs`, and `Array jobs`.
=> Updating the serial page in Triton tutorials

triton/tut/array.rst, triton/tut/serial.rst
I restructured the `array.rst` documentation and incorporated the Pi script into the on-page
examples. There are still some todos and things to consider:
- The `Reading input files` section is not changed much yet. I wanted to use the `pi_aggregation.py` script for this part, so I will make the changes after the script is reviewed.
- There was an allusion to parallel array jobs that I removed. I thought it's best to have it in the parallel documentation. What do you think?
- I will add a short example for 2D sampling and `%N` use cases. 
- Perhaps an exercise regarding the use of `--ntasks` and how it differs from job array should be added?
=> Updating the array jobs page in Triton tutorials

aalto/remoteaccess.rst
Apparently server with name amor.nbe.aalto.fi does not exist.
=> Correction to host name of NBE department server

triton/tut/gpu.rst
I tried to reorganize and update the documentation. 
I included a submission script compatible with the [CUDA helloworld](https://github.com/AaltoSciComp/hpc-examples/blob/gpu-example/gpu/helloworld.cu) in the documentation.
There are a few things I should change soon:
- Should I put all the Python scripts for the examples in the hpc-examples repo? To be cloned alongside other examples?
- Change the anaconda version for the PyTorch example.
=> Updating the GPU computing tutorial page

triton/tut/connecting.rst, triton/usage/ssh-fingerprints.rst
Found with these commands:
- `ls /etc/ssh/*.pub | xargs -i ssh-keygen -l -f {}`
- `ls /etc/ssh/*.pub | xargs -i ssh-keygen -l -f {} -E md5`
- `ssh-keyscan triton.aalto.fi`
Is this a good format?
Closes: #90
=> triton/: Add Triton ssh fingerprints

triton/tut/storage.rst
- This is either a recent or upcoming change.
- Recommend requesting an Aalto computer or using VDI.
=> triton/tut/storage: note that SMB mounting may only work from Aalto laptops

triton/tut/parallel.rst
This commit was missing from the merged version.
=> triton/tut/parallel: Added information on process oversubscription

triton/tut/connecting.rst
- apparently it was introduced in OpenSSH 7.2, from 2016.  Should be
usable by now.
=> triton/tut/connecting: mention and recommend ssh -J

rse/become-a-rse.rst, rse/community.rst, rse/index.rst
- Add general requirements for our RSEs, to be used as a reference
from the job advertisements.
- @aalto-kenny
=> rse/: add become-a-rse, split from community

training/scip/summer-kickstart.rst
Just adding the links to HTCondor tutorials and documentation. I have checked that the links work.
=> Kickstart HTCondor links

aalto/linux.rst, triton/tut/modules.rst
- Explain ``module load triton-modules`` in several key places.
=> aalto linux: document triton-modules

rse/index.rst
- Link the history of RSEs
- Clarify relationship between SciComp's RSEs and nordic-RSE
=> rse/index: Add link to history of RSEs

README.rst, aalto/index.rst, scicomp/index.rst, triton/index.rst
* "Triton user guide" -> "Triton cluster".
"user guide" seems unnecessary here, there is no longer any
confusion.  "The Triton cluster" would be more appropriate but "the"
is an unnecessary word.
* "The Aalto environment" -> "Aalto tools".
This always seemed like a weird name to me.  Just "Aalto" seems too
broad, "Aalto tools" is what I settled on for now.  It could also be
"Aalto environment" but I don't quite like that.  Any ideas?
* "Scientific computing" -> "Scientific computing tips".
"Scientific Computing" was too broad, everything here is scientific
computing.  I also considered "Scientific computing in general".
* "About these docs" -> "About this site"
Seems simple and reasonable... I'm wondering if this could be put
into some other subsection, but it probably best goes where it …
=> Adjust primary names in the table of contents

README.rst, aalto/welcomeresearchers.rst, index.rst, triton/accounts.rst, triton/help.rst, triton/index.rst, triton/tut/intro.rst
- Remove old links to science-it.aalto.fi (except link that don't
currently have a replacement)
- Take the opportunity to update some of the general ASC
meta-information on the main pages, since this is now the main page.
=> Remove old links to science-it.aalto.fi and improve ASC description

help.rst
- A user had requested one page to use to answer "who should I ask for
help and how?", since there are so many different places and email
addresses.  This is the first step of that.
- This should eventually be integrated with:
- https://scicomp.aalto.fi/aalto/welcomeresearchers/ (and welcomestudents)
- https://scicomp.aalto.fi/triton/help/
- and information de-duplicated
- RSEs should be more prominently mentioned.
- To review
- Does this present a fair picture of the situation?
- Have I forgotten anything the services do?
- Have I forgotten any services that need to be mentioned?
- Have I provided good advice on triaging to the different services?
- Is it too long?  Can it be made much shorter?
- Suggestions for de-duplicating.
=> Add a new "/help" page.

aalto/jupyterhub.rst
- Old page, but newer than this paragraph.  Add the link, since it
should be here.
=> aalto/jupyterhub: link /scicomp/jupyter-pitfalls

aalto/jupyterhub-instructors/faq-hints.rst, aalto/jupyterhub-instructors/nbgrader.rst, aalto/jupyterhub-instructors/request-course.rst
- The basic text comes from @Sefriol, I've adapted it for this.
=> aalto/jupyterhub: Add link to gitlab organization for course notebook

conf.py
- Add an if to remove depreciation warnings on sphinx 3.0, while still
supporting old sphinx with is the default in our current default
Ubuntu at Aalto.
=> conf: Support sphinx 4.0

triton/usage/jobs.rst
- It's very out of date
- Instead of exact info, give a range and direct to the slurm.conf
file for up-to-date info.
=> triton/usage/jobs: Update GPU billing weights

_templates/footer.html, conf.py
- Add a text that says " This site is made for Aalto Scientific
Computing, but we welcome contributions that make it more useful to
others, too."  Outside readers shouldn't think this is "us or them",
while specific to us we can make it useful to others, too.
- set html_show_sphinx to False to keep the footer from growing too
long.  Instead, include it in this new paragraph.
=> footer: Add explicit "welcome contributions" footer

about/cs-it.rst, about/index.rst
- Draft with some basic info
- To review
- What else do we do?
- Is the "work for us" appropriate?
- Add our group members to the about page, if desired.
- Can look at the science-it page for inspiration of what else can
go here
- What else should be moved to scicomp.aalto.fi instead of internal
wiki?
=> about/cs-it: Add initial CSIT page

help/community.rst, help/index.rst, rse/community.rst
- Before, there was /rse/community, but the community is actually
broader than just RSEs.  Move it to help.  The old page stays there
for the time being.
=> /help/community: centralize community info, add page

conf.py, requirements.txt
- See #164 for reasoning.
- In short, web accessibility checker showed that there wasn't enough
contrast in different elements.  This improves it by overriding the
theme some, but is not a proper fix: it should be fixed upstream here:
https://github.com/readthedocs/sphinx_rtd_theme/issues/971
=> requirements: Add color contrast module, replaces #164

meta/check-warnings.py
- "toctree contains reference to nonexisting document" becomes a hard
error, not a warning.
- To revew: not much I think.
=> meta/check-warnings: Add error for toctree error

rse/index.rst
- The old "who" link is obselete and has a SSL error, and wasn't that
good anyway.
- Promote the "history of RSEs" which was a better link anyway, while
leaving the old link at the bottom (hoping it will work eventually).
=> rse/index: Adjust RSE links

help/community.rst, rse/community.rst
- As discussed with @rantahar, we can direct all Aalto scicomp people
to the Nordic-RSE Finland chat.  Can rethink this if too many people
show up.
- To review:
- Is the wording good?  Is the whole community section too long and
confusing?
- @rantahar: is this good wording?
=> {help,rse}/community: link to Nordic-RSE weekly chat.

training/scip/python-for-scicomp.rst
- I think instead of local installation, jupyter.cs is sufficient for
most of the course.  We can suggest this as an option.
=> training/scip/python-for-scicomp: jupyter.cs sufficient for the course

training/scip/python-for-scicomp.rst
- Instead of code of contact, I have been thinking of "community
standards" lately, which says the (positive) things you should do
while also saying what to do if things go wrong.
- In the lecture, this is the time where we give the base standards
and how we expect people to help each other, how breakout rooms
work, etc.
- To review: everything, is anything missing?  What needs to be added?
(though this is short, we can't have everything.  I intend to expand
this to a larger standard project-wide text).
=> training/scip/python-for-scicomp: Add community standards

rse/procedures/index.rst, rse/procedures/time-tracking.rst
- Problem: we need to track time somehow, so that we can tell each
deparment how much benefit they are getting, and how much funding
each group is providing and which department's funding it replaces.
- This is an initial light suggestion for how we can manage RSE
projects using Gitlab.  Gitlab isn't exactly the right platform, but
it is open and the same we should be using for other stuff.
- We would then closely manage the projects using labels and other
scripts using the Gitlab APIs, to produce reports.
- To review: is this even a good idea?
=> rse/procedures/time-tracking: Suggestion for RSE time mgmt via Gitlab

news/index.rst
I would like to update the /news/index.rst daily to reflect news/upcoming events or other things worth mentioning.
I am unsure about some of the syntax (will the toctree work?) but hopefully it's quick to fix by who reviews this :)
=> editing the news page to make it more uptodate reflect daily news

news/garage.rst
- This removes the weird toctree effect where navigating to
/help/garage makes you end up in /help/garage.
- It uses raw HTML to redirect it, which I think isn't ideal but
simple and seems to work locally, and I hope redirects search
engines to the right place.
- There are HTTP redirects in readthedocs, but then we stay locked in
to readthedocs.
- Review: consider if this is a good idea and if there is a better
Sphinx option.
- Update: I just saw
https://github.com/wpilibsuite/sphinxext-rediraffe, which is
released less than a month ago, which is why I didn't see it
before.  Perhaps consider that instead of this.
=> news/garage: Redirect /news/garage/ to /help/garage/

training/scip/data-analysis.rst
This PR changes the name of the data analysis course to reflect the change in the materials.
=> training/scip/data-analysis: Updating data analysis course name

rse/procedures/advisory-board.rst, rse/procedures/index.rst, rse/procedures/units-info.rst
- Add two new pages, to be updated later.
- Advisory board: a group that steers the program.  This page
contains it's composition and meetings.
- Units: tracks which units are currently members and provide basic
services for their researchers.
- Review: general sanity check
=> rse: add units-info and advisory board pages

rse/how-we-work.rst
- I made this myself, and I hope it's fast enough to get a quick
overview of a project's data processing, without being too
bureaucratic.
- Of course this doesn't apply to every project, but for those that we
do, it seems relevant.
- Review: is this a good idea?  Is there some other option?
=> rse/how-we-work: Add link to the A4 DMP template

conf.py
- One of my goals has been to avoid requiring extensions to build the
site (fall back to plan sphinx, so it will work on a normal Aalto
Ubuntu).
- Don't special-case optional extensions so much (this makes it easier
to add more later, which will come soon)
- Use sphinx_gitstamp only on ReadTheDocs.  This saves a lot of time
when building, since the i/o access of finding the last times on
every build is surprisingly large.
- Review:
- May be easier to review each commit separately
- General check
=> Improve extension handling: make general, speed up

rse/request.rst
- Since we made Gitlab private, the statement for how to contact us is
wrong.
- Change it to focus on email, but don't fully remove the old stuff
yet.
- Review: I'm making this so we can make it correct in the short term,
but I'm not sure if we either keep this, revert the Gitlab change,
or wait to recommend something else.
=> rse/request: Remove Gitlab mention

rse/procedures/time-tracking.rst
- Each RSE may find their own way to track time, but we need the data
to be compatible, so that we can merge it together.
- Here, define a semantic data format that *can* be standardized, so
that we expect each RSE to provide information that matches this, so
that it can be merged with our data.
- Review: is this a useful format?  This is just my first thought.
=> rse/procedures/time-tracking: Add proposal of semantic data format

rse/units.rst
- Since title was not a higher level, all sections appeared in the
table of contents.
- Review: does CI pass?
=> rse/units: fix RST syntax, page heading is heading

aalto/jupyterhub-instructors/request-course.rst
- Add a copy-and-paste a course template, which can be used to
expedite requesting courses.  This is in the same format we need, ot
make it quick to enter.
- Review: general check, to be iterated.
=> aalto/jupyterhub-instructors/request-course: Add a course template

conf.py, requirements.txt
- These allow better buttons and tabs for exercises (and other places)
- Review:
- general check
- do we want to preserve the ability to build without any extensions
installed?  Right now you can, and it will just degrade the output
somehow.  Is an immediate hard error better?
=> Add sphinx-{lesson,tabs,copybutton,togglebutton} extensions

aalto/jupyterhub-instructors/request-course.rst
- guru email address was missing, add it.
- Review: do we want email address listed?
=> jh-instructors/request-course: Add email address

triton/accounts.rst
- If you aren't already logged in to Aalto auth, following the link
will lead you to the central self-service page, not the exact form.
- Add name of page to clarify for these peple.
- Review: quick read
=> triton/accounts: Add name of Triton account request form

triton/examples/python/python_openmp/python_openmp.rst, triton/tut/parallel.rst
This PR fixes some of the parallel examples on our tutorial page. Especially the MPI examples.
=> triton/tut/parallel: Added better MPI examples

triton/usage/quotas.rst
- This was missing, despite being one of the common commonds to run
when checking quota.
- List this as a thing to check home quota, but not Lustre.  To
prevent people from getting too creative and running on scratch
without thinking about it.
- Review:
- How else should this page be adapted for home quotas?
=> triton/usage/quotas: Add a du command to check home quota

aalto/aaltodata.rst
- Previously, it didn't mention that group membership remains after
a possible employment contract ends.
- Review:
- general read
- Is there anywhere else this should be mentioned?  There is a lot
of text and maybe the important parts are too hard to find.
=> aalto/aaltodata: Mention that users must be removed from groups

triton/tut/parallel.rst
- There was a persistent warning that should go away now
- Review: are there CI warnings?
=> triton/tut/parallel: fix highlighting by changing lexer to bash

aalto/zulip.rst
There was some confusion from a new user as to what to do to login to scicomp.zulip.cs.aalto.fi: she could login with her Aalto account, but was then prompted to register for a Zulip account/profile, because no existing profile was found. I guess you should just register one and then the Zulip profileis linked to your Aalto credentials?
=> Add some instructions for registering a new Zulip account

aalto/jupyterhub-instructors/index.rst
- These docs are good and this is a commercial service, could be
useful to our instructors.
=> aalto/jupyterhub-instructors: add link to Noteable docs

rse/how-we-work.rst, rse/index.rst, rse/request.rst
- Use our new text here
- Review:
- Should it be made shorter?  I have tried before to make the intro
text as short as possible, and this amount is making me think it's
too long.
- The aalto.fi text is designed to be very high-level.  I think this
could be direct to the point, which would make it shorter as well.
=> rse/index: Update front paragraphs from aalto.fi pages

triton/usage/singularity.rst
This PR removes outdated information on automatic singularity image building until the document is up-to-date.
=> triton/usage/singularity: Remove outdated information 

tech/index.rst
- One: Sphinx documentation (should this be combined with the earlier
general "support" talk?  I think that if we do, it would end up
taking too long.)
- One: Online teaching practices and CodeRefinery
- Review: general read, this is dynamically updated as we make plans
=> tech/index: Add two proposed talks by rkdarst

about/index.rst, index.rst
- Reduce items on sidebar, limit links on front page to those that are
important.  The remaining links are put under the about/ section
toctree (which is where I thought they could be anyway...)
- Rename "About ASC" to "About" to reflect bigger picture.
- Review: is this a good idea?
=> index: Reduce the number of items on the sidebar

triton/usage/conda-and-cuda.rst
This PR contains a new special document on how one should go about compiling CUDA extensions to codes that are installed via conda.
=> triton/usage/conda-and-cuda: New document on conda and CUDA compiling

triton/apps/aims.rst, triton/apps/matlab.rst, triton/apps/vasp.rst, triton/examples/r/r_serial.slrm, triton/tut/array.rst, triton/tut/interactive.rst, triton/tut/parallel.rst, triton/tut/serial.rst, triton/usage/general.rst, triton/usage/localstorage.rst
- Once in a garage, someone was confused about the default units.  An
easy way to solve this is to always specific them.
- Add `M` as the dafult unit to every --mem and --mem-per-cpu, if not
already specified.
- Found by clever grepping.
- Review
- Do we want to do this?
=> Switch all --mem units to M (instead of unspecified)

training/scip/summer-kickstart.rst
- as discussed in garage, we can give some follow-up links not part of
the course but that may be useful for people to watch on their own.
- Link to two relevant Research Software Hour videos.
=> training/scip/summer-kickstart: Add follow-up suggestions to the course

training/scip/summer-kickstart.rst
- Add a new "how to attend" section at the top.
- There is slight duplication with stuff at the bottom, but top is
summary, bottom is detail (I hope).
- More adjust at bottom needed later
- Review: worth a read and some thought.
=> training/scip/summer-kickstart: How to attend

training/scip/summer-kickstart.rst
- Make the day 1 intros more explicit on timing
- Readjust parallel theory at the end
=> training/scip/summer-kickstart: Schedule updates from meeting

triton/apps/jupyter.rst
- An extra command is needed in the case that the IJulia library is
already installed.
- As discovered in garage.
=> triton/apps/jupyter: IJulia kernel installation instructions

scicomp/ssh.rst
- This is one of the more useful things, but has always been missing
from the ssh page.  Add it now.
- Review: worth a more detailed read and ensure that things make sense.
=> scicomp/ssh: Add section dedicated to ProxyJump

triton/apps/jupyter.rst
- This started as a clarification that `ipykernel` has to be installed
in any environments, but then become a slightly larger
rearrangement.
=> triton/apps/jupyter: Clarifications about Jupyter kernels

rse/checklists/project-done.rst, rse/index.rst
- A new page to go over end-of-project matters
- Initial contents from RSE meeting
- Review: what else could be added?  I haven't thought that much about it.
=> rse: add "project done" checklist

triton/apps/python.rst
- In the issue, it was noticed that `conda activate` doesn't work in a
batch script, since .bashrc isn't sourced.  Here, I comment a bit
more about why we do `source activate`, hiding details in a toggle
box.
- Triton issue #873
- Review: should the toggle box be removed since it is too verbose?
=> triton/apps/python: Info about conda activate in shells

rse/become-a-rse.rst, training/index.rst, training/scip/summer-kickstart.rst, training/scip/summer-kickstart/future.rst, training/scip/summer-kickstart/intro.rst, triton/accounts.rst, triton/index.rst, triton/tut/intro.rst
=> Adjust Hands-on scicomp url to hands-on.coderefinery.org

rse/index.rst
- I am adding it here because aalto.fi search never works well, so I
need a better way to find the page.
- automerge
=> rse/index: Add link to our aalto.fi page

help/garage.rst
Just a suggestion to clearer phrase what "services" we offer, and what questions we can answer. Also encouraging people to come even if it's not their focus days since (at least to my impression), someone who can answer a specific question is commonly around, and I think it's better not to wait for the right focus day to ask your question.
=> Update to garage description

triton/tut/storage.rst
Adding another (potentially convenient) way of mounting triton filesyystems remotely using sftp and proxy jumps.
=> Adding sftp-mounting to storage tutorial

aalto/coderefinery-setup.rst
- Previously headings were same as page title, meaning that each
section appeared in the higher level table of contents.
=> aalto/coderefinery-setup: Adjust heading leavels

training/scip/python-for-scicomp.rst
- Link to new livestream how-to-attend page.
- De-emphasize some of the Zoom info
- Whitespace cleanup
=> training/scip/python-for-scicomp: Update how-to-attend basic info

triton/index.rst
- Learning by example is very important, and one complaint was that
the docs are too tutorial-focused.
- Move this higher (even above tutorials) to empahsize it more.
- This may also motivate us to develop this section more.
=> triton/index: Move the reference/examples section higher

training/scip/python-for-scicomp.rst
- Has to be adjusted for livestream
- Add other private means of contact (chat, coderefinery support).
- Review:
- read if the message is right?
- are the contact methods good?
=> training/scip/python-for-scicomp: Adjust community standards section

triton/usage/gpu.rst
Adding an admonition to stress, that if submitting a job using srun (in a batch script) you need to re-request the GPU ressource.
=> Adding Info-Box for GPU jobs

triton/apps/python.rst
Putting the warning above the introduction of the command makes it more obvious and avoids people stopping reading after the command is introduced.
=> Put the warning above introducing pip install user

meta/check-warnings.py
meta/check-warnings: Promote several warnings to errors
- This improves CI, I noticed these errors which should normally fail
CI today
=> meta/check-warnings: Promote several warnings to errors

triton/tut/applications.rst, triton/tut/array.rst, triton/tut/connecting.rst, triton/tut/gpu.rst, triton/tut/interactive.rst, triton/tut/modules.rst, triton/tut/monitoring.rst, triton/tut/parallel.rst, triton/tut/serial.rst, triton/tut/storage.rst
- Add the generic instructions at the top - suitable as a summary of
content for new people, but the main use is that "someone who
already knows everything except the content on the page can see what
they need".  It is also good for people coming back to the page who
just need to copy commands.
- Copy-paste templates could be added to several of the pages,
possibly.  But then we can ask, should each template include what
was introduced in previous pages?  I would say that for longer
templates, peolpe can scan the page to find them.
- Review
- Each one could should read to see what may be missing from there
(but should be kept short with minimal examples) - I have not done
a second reading yet.
- Likewise, what should be removed from the generic instructions?
- We could debate if this even …
=> Add generic instructions to all tutorial pages

training/index.rst, training/scip/index.rst, training/scip/intro-linux-aalto-computing.rst, training/scip/winter-kickstart.rst
Registration links added and updated the dates. 
There is still "old" content that can be updated later.
Ideally one of the instructors can approve the PR
=> minimum update for making the winter kickstart pages live

triton/usage/faq.rst
- Notes on the error messages
`Unable to allocate resources: Requested node configuration is not available`
and
`Required node not available (down, drained or reserved)`
- This is based off of text originally by @JMuff22 - thanks!  This has
a proper `Author:` credit which will be added to the git history,
please approve the PR before we merge it.
=> triton/usage/faq: notes about nodes not being available

aalto/git.rst
Updating link to point to the new Aalto version quickstart page.
Resolves #448
=> Updating link to new quickstart page

triton/tut/connecting.rst, triton/usage/ood.rst
- Template of a basic docs page
- Mostly empty, to be filled out more later
- Review: general check, mostly merge + iterate
=> triton/usage/ood: Add OOD page with some basic information

triton/tut/monitoring.rst
- makes page less verbose by default
- review: automerge
=> triton/tut/monitoring: Make a long reference thing toggleable

triton/apps/python.rst
At least to me, the conda environment/package folders being visible files is somewhat distracting, and I think "hiding" them on scratch (like they are in home) would make sense. This is just a suggestion though.
=> Change conda on scratch to hidden folders

training/scip/index.rst
- Proposal: add links to the old courses.  While most of these pages
get updated so no longer are active for the year in question, I seem
to be always looking for these pages, and they aren't linked.
- This is probably good for search engine visibility
- Problem: they get updated for later years.  But still, perhaps most
people looking for what they could expect if they took the course
again (and it provide a starting point for looking into the git
history)
- I think this is more useful than a problem
- Review: decide if we should do tihs.
=> training/scip/index: add links to old courses

help/group-meetings.rst, help/index.rst
- Add a new page for group meetings - the idea is that having some
public text to link to makes sending group meeting emails easier.
- The topics are seeded from the CS group meetings wiki page, but most
other text is somewhat new.
- Page created and linked in the help/ section, but I'm not sure if
that's the right place.  I might do it in about/ instead?  Though
user group meetings are in help/.
- Review:
- Is it worth having a page on this?
- Is the text useful?
- Is it in the right section?
=> help/group-meetings: Add a page for group meetings

training/scip/index.rst, training/scip/software-design-2021.rst, training/scip/software-design.rst
https://scicomp.aalto.fi/training/scip/software-design/ still points to the 2021 course. This PR updates the link to 2022 version, and updates the archived version to point to software-design-2021.
=> Update main link to the software-design course to 2022

scicomp/ssh.rst
The current tutorial creates a non default name key, which needs to be indicated explicitly in the config. While this is mentioned before the Sample config file, it is missing in the config and I think the tutorial should be consistent, so that, if you follow all steps it works in the end.
=> Adding IdentityFile parameter for consistency

triton/usage/singularity.rst
- Revise frot matter
- Separate into two sections: using it via our modules and using it
yourself with raw commands.
- It tries to be more clear and support the "using it yourself" system
more, but other than that there are few fundamental changes (yet).
- Review: general check, or merge and iterate
=> triton/usage/singularity: Update singularity docs

_static/theme_overrides.css, help/garage.rst, help/index.rst
- The page has a lot of text, and it can be intimidating on where to
get started.
- This adds a table to the top which has common types of questions
(getting started, small things, big things, etc) and describes what
to do for questions at this scale.
- Review
- Could be merged and iterated
- Think about if anything is missing.  And especially, can it be
made shorter?
=> help/index: Create an overview table at the top

training/scip/kickstart-2022-summer.rst
- Round out the schedule some more, make it look more interesting.
- Remove SciComp workflows and tools of SciComp (put under video lists)
- Add "about us", "full example workflows", "cooking metaphors to
parallelism", and "environments in Python and R", all 25 minutes.
Unsure if these are the best options but looking at old chats I see
them mentioned and they seem like good options.
- Review: analyze, maybe quick merge and iterate.
=> training/scip/kickstart-2022-summer: Proposal for schedule update

triton/apps/gcc.rst, triton/apps/intelcompilers.rst, triton/examples/c/hello-world/hello.c, triton/examples/c/hello-world/hello_gcc.rst, triton/examples/c/hello-world/hello_icc.rst
This PR contains new pages for gcc and intel compilers.
=> triton/apps: New pages for gcc and Intel compilers 

triton/apps/mpi.rst, triton/examples/mpi/hello.rst, triton/examples/openmp/hello_omp/hello_omp.sh, triton/examples/python/python_openmp/python_openmp.rst, triton/examples/python/python_openmp/python_openmp.sh, triton/examples/python_openmp.rst, triton/ref/mpi-warning.rst, triton/tut/parallel.rst
This PR does the following:
- Adds a new page that tells about available MPI installations.
- Updates the parallel tutorial with new information.
- Updates multiple module names in examples.
=> triton/apps/mpi: Adding a new page for MPI installations

triton/ref/slurm_status.rst
- This was missing from the Slurm list but is very useful.
=> triton/ref/slurm_status: Add the GPU utilization command

triton/apps/jupyter.rst
- This was suggested during garage to remove the number of mental
jumps needed to know what to do.
- Review: is it too long?  if not, automerge
=> triton/apps/jupyter: Add pointer to make environment first, before kernel install

triton/apps/jupyter.rst, triton/examples/python/simple_python_gpu.sh
Adding a short example on converting jupyter notebooks to python and running them in the queue. 
Could be useful for people who start using triton via jupyterhub but then notice that they need to run jobs on e.g. gpu nodes or similar situations.
=> Adding jupyter to python example

training/scip/workflows-2023.rst
- Add a page so we can start linking to it
- The course and page needs a better title than "Workflows", I think.
- We should make a registration page asap, even if we don't know the
dates
- Review: small fixups but merge quickly to iterate.
=> training/scip/workflows-2023: Add template page

triton/apps/python-conda.rst, triton/apps/pytorch.rst, triton/apps/tensorflow.rst, triton/examples/cuda/cuda_override_hint.rst
Seems like there are several versions of e..g. tensorflow now, where simply specifying the cuda version is insufficient and you need to actively override the conda CUDA detection mechanism. 
Added this to the docs.
=> Adding OVERRIDE to doc

index.rst, news/index.rst
Let's update the news.
Making the login3 node upgrade more public and pointing to the Python for Scientific Computing course
=> Updated news page

triton/ref/connecting.rst, triton/tut/connecting.rst
Currently the different connecting pages still refer windows users to Putty.
I changed this to point to powershell/Command line, which work fine on windows 10 systems which do support and provide an openssh client.
=> Updating Connection to rather use powershell/cmd instead of putty

triton/accounts.rst, triton/usagepolicy.rst
- As discussed in our chats and meetings, this adds the clarifications
that we have found.
- Review: most text is copied from other places, but worth reading to
check in detail.
=> triton: Add description of account purposes

_templates/layout.html
- Common problem: pages are old or out of date.  How can we lower the
threshold for reporting this?
- This adds a link to create a new github issue, with some stuff pre-filled.
- Is this the best way to manage it?  Should there be a private way to
submit issues (that doesn't need a github account) too?
- Someone who can do styling could take a look and see if it looks
good enough.
=> _templates/layout: Add a way to request improvements to the page

_templates/breadcrumbs.html, _templates/layout.html, conf.py, index.rst, triton/ref/index.rst
- Previously, this was in the footer of each site.
- Now, instead of "Edit or Github", it says "Last edited %Y %b %d",
and if the page is edited before a configurable threshold, it will
put the date in `darkred`.
- This doesn't solve unmaintained pages, but it provides a more clear
indication to users for what is up to date or not.  I think that
keeping everything up to date is almost impossible, so instead let's
make it easier for users to understand what is recent and not.
- Review: check preview and see.
=> At the top of pages, list the last edited date

rse/portfolio.rst
- This as a reasonable example of an internal project, and might
inspire other teams to contact us with similar types of projects.
=> rse/portfolio: Add version.aalto.fi script project

triton/tut/gpu.rst
- Obsolete for some time now, the bug has been fixed.
=> triton/tut/gpu: Remove the "don't use srun" warning from the top

aalto/jupyterhub-instructors/nbgrader.rst
Noteable docs are linked only in the JupyterHub page. It is better to make it more visible by adding it to the main nbgrader page.
=> aalto/jupyterhub-instructors: Link to Noteable docs in Nbgrader basics

triton/tut/serial.rst
The example could use the more beginner friendly (easier to understand) --mem instead of --mem-per-cpu.
Also, the example could explicitly set the number of cpus with --cpus-per-task or the default value of cpus-per-task=1 should be mentioned.
=> Update serial.rst: change --mem-per-cpu in example batch script to --mem, add --cpus-per-task

aalto/htcondor.rst, aalto/index.rst, about/index.rst, training/index.rst, triton/apps/matlab.rst
This PR removes HTCondor from various pages. Old HTCondor-page  is left for now as some training materials refer to it.
=> Remove HTCondor

triton/examples/pytorch/pytorch_mnist.rst
Fix tensorflow/pytorch typo in file name
=> Fix typo in pytorch_mnist.rst

triton/tut/array.rst
Add missing word in `array.rst`
=> Fix typo in array.rst

training/scip/kickstart-2023.rst
Since it's likely that a lot of people need this info due to scheduling, I moved it under practical information instead of being slightly buried under schedule.
=> Moved "if you miss day1" infobar to practical information.

triton/apps/importantnotes/resetconda.rst, triton/apps/python-conda.rst
- "console" highligher makes `$` prompt un-selectable
- while not done here, `.. highlight:: console` at the top makes
default literal blocks highlighted that way.
=> Formatting and highlighting on Python pages.

scicomp/ssh.rst
- I would sometimes need to refer to multiplexing, so mention it.
(especially with upcoming Aalto changes).
- But don't make it recommended or easy.
=> scicomp/ssh: Add section on Multiplexing

aalto/git.rst
- Closes: #665
- Plus a few more small updates for links
=> aalto/git: Update links for 2023

aalto/jupyterhub-instructors/nbgrader-hints.rst
- Note a feature that's added to not scale grades to 100 when
exporting.
- Also note that the email conversion isn't needed usually.
=> aalto/jupyterhub-instructors/nbgrader-hints: Note about grade scaling

triton/examples/r/r_openmp.rst
Updating the link to the R benchmark script, the old one is broken.
=> Fixing R example link

triton/apps/speech2text.rst
- Mainly directs to the github pages site, but makes it searchable from aalto.fi
=> speech2text landing page

scicomp/ssh.rst
`ssh-copy-id` doesn't support ProxyJump or `-J` option directly. The only way is passing `-o` to use `ssh` options like ProxyJump.
This PR fix this issue for new users to follow the ssh guide easier.
=> Fix ProxyJump with ssh-copy-id

triton/apps/jupyter.rst
There's a differenec between:
- running python in an environment (without PATH set)
- setting PATH etc and then running python in the environment
envkernel (with the rigth options) does the second
The previous instructions tried to load Lmod but didn't do the second.
=> triton/apps/jupyter: Fix instructions for R kernel through conda

triton/apps/mpi.rst, triton/examples/lammps/build/build_basic.rst, triton/examples/lammps/build/build_most.rst, triton/examples/lammps/indent/lammps_indent.sh, triton/examples/mpi/hello.rst, triton/tut/parallel-mpi.rst, triton/usage/singularity.rst
This PR updates OpenMPI version to 4.1.5 as there are problems in the 4.0.5 module.
=> Update openmpi version to 4.1.5

aalto/remoteaccess.rst
Cisco VPN now requires User Agent to contain the word AnyConnect to work.
https://scicomp.zulip.cs.aalto.fi/#narrow/stream/4-general/topic/VPN.20connection.20problem/near/276672
=> update instructions for openconnect

aalto/remotejupyter.rst, triton/apps/deeplearn.rst, triton/apps/gurobi.rst, triton/apps/jupyter.rst, triton/apps/keras.rst, triton/apps/python-conda.rst, triton/apps/python.rst, triton/apps/pytorch.rst, triton/apps/spyder.rst, triton/examples/multilang/python/parallel.sh, triton/examples/multilang/python/parallel_fun.sh, triton/examples/multilang/python/serial.sh, triton/examples/multilang/python/serial_grouped.sh, triton/examples/python/ipyparallel/ipyparallel.sh, triton/examples/python/python_openmp/python_openmp.rst, triton/examples/python/python_openmp/python_openmp.sh, triton/examples/python_openmp.rst, triton/examples/pytorch/pytorch_mnist.rst, triton/examples/pytorch/pytorch_mnist.sh, triton/examples/tensorflow/tensorflow_mnist.rst, triton/examples/tensorflow/tensorflow_mnist.sh, triton/ref/condaactivate.rst, triton/tut/modules.rst
This is a PR that will update references to anaconda to scicomp-python-env.
NOTE: Please do not merge before Triton v3 is in production
NOTE2: This PR does NOT update references to anaconda in the non triton specific instructions of the doc, since those also refer to workstations etc. We should probably work towards harmonization here, i.e. having the workstations (and thus aalto linux) be set up to use a new module, otherwise we start getting out of sync.
=> Updating anaconda -> scicomp-python-env in triton documentation

triton/apps/python.rst
This updates the python page to provide a separation on installing packages. 
No installation should happen with scicomp python env. If you need more packages -> use mamba
Separation is:
"General python" : module load scicomp-python-env
"Need more packages": Write an environment file and use module load mamba
=> Clarifying use of python installation

conf.py
- Not labeled descriptively, also most of the site isn't designed for
scolling forward and backwards.
=> conf: Remove next and previous buttons

triton/tut/array.rst
The referenced filename didn't match the actual file in the `hpc-examples` repo.
=> Fix filename in array.rst

triton/apps/python-conda.rst, triton/apps/python-ipyparallel.rst, triton/apps/python.rst
- All triton/apps/python.rst was moved away and relevan things were moved back.
- Remove redundant Conda stuff from the main Python page.  Instead
link python-conda.
- Split ipyparallel to a new page python-ipyparallel
- There are still some assorted examples in the main Python page.
- Most of the same data is there, including the advanced warnings.
=> Restructure Triton Python pages (emphasize mamba, remove conda redundancy)

data/requesting.rst
- Remove the long intimidating checklists
- Instead, write the same info into free-form templates that are
suitable for any department and also ITS storage spaces.  People are
asked to read and adapt to their needs, which hopefully has less
barrier.
=> data/requesting: Revise the templates for requesting storage space

triton/examples/lammps/build/build_basic.rst, triton/examples/lammps/build/build_most.rst
- The voropp library isn't on new-triton so I removed it, I don't know
if it will build or not.  We can let a user build finish and see if
it goes through.
=> triton: lammps: modules for new-triton

triton/ref/connecting.rst, triton/tut/connecting.rst
- OOD now has graphics +
- It's still mentioned as a remote data access method which seems OK
- It's still mentioned in `triton/tut/interactive.rst` but that
section needs revising later anyway
- review: automerge 3day if no other comments
=> triton: remove VDI as a connection recommendation

aalto/generative-ai-tools.rst
The ITS page is confusing and hard to find.
The updated link has all the information (from how to request to API usage, costs, endpoints etc). The previous link doesn't provide the API information, just how to request.
(Although the structure of the ITS page is confusing, I think having this link is better).
=> Fix Azure OpenAI API link

training/scip/python-for-scicomp-2024.rst
Also mention Ashwin and Yonglei
=> Add ENCCS as partner for python-for-scicomp-2024

training/scip/python-for-scicomp-2024.rst
- fix link to plotting lesson
- profiling and productivity tools are two episodes
- reverse order of instructors
=> fixes in python course schedule 2024

triton/apps/index.rst
- A/B/C for globally installed software
- E/F for user installed software
- We will separately make a list of A-software
=> triton/apps/index: Update the "support levels" table based on discussions

triton/apps/jupyter.rst
I notice a section in the documentation of jupyterhub through OOD that seemed a) at least somewhat spurious, b) the example seemed to be using modules that are no longer there, and therefore confusing. Currently this is removing the whole section, I'd be happy to rework, if someone thinks this should stay
=> removed a section that seemed spurious

triton/apps/llms.rst
WIP.
Suggestion to make the LLM page more concise, removing obsolete sections (llama checkpoint sections).
=> Update LLM section for winter kickstart

aalto/windows.rst
inside.aalto.fi doesn't exist anymore, found a somewhat similar replacement for the link.
=> Update Aalto Windows link
